name: Create Pull Request

on:
  repository_dispatch:
    types: [create-pr]


jobs:
  Create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Clone release branch to create pull request
      run: |
        git checkout ${{ github.event.client_payload.ReleaseBranchName }}
        git branch ${{ github.event.client_payload.ReleaseBranchName }}-docs
        git push origin ${{ github.event.client_payload.ReleaseBranchName }}-docs --force

    - name: Create pull request for ${{ github.event.client_payload.ReleaseBranchName }}
      id: create-pr
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let response = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ github.event.client_payload.PullRequestTitle }}",
            head: "${{ github.event.client_payload.ReleaseBranchName }}-docs",
            base: "${{ github.event.client_payload.PullRequestBase }}",
            body: `${{ github.event.client_payload.PullRequestBody }}`
          });
          return response.data.number

    - name: Request reviewers
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        github-token: ${{secrets.PRAPPROVAL_SECRET}}
        script: |
          github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.create-pr.outputs.result }},
              team_reviewers: ['runner-images-team']
          })
